name: Lint
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install NPM dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
