name: Require SemVer Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main
jobs:
  label:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "semver:patch, semver:minor, semver:major"
